#!/bin/bash
sudo apt update && sudo apt install slapd ldap-utils -y
# Añadimos password...

sudo dpkg-reconfigure slapd
# Omitir configuración del servidor OpenLDAP --> <No>
# Introducir el nombre del dominio DNS --> doncom.com
# Nombre de la organización --> DonCom Organization
# Contraseña del administrador --> password
# Confirmar contraseña --> password
# Desea que se borre la base de datos cuando se purgue el paquete slapd --> <No>
# ¿Desea mover la base de datos antigua? --> <Si>

