---
- name: Browsing tools installation playbook
  hosts: all
  become: yes
  tasks:

  - name: Update package list
    apt:
      update_cache: yes

  - name: Install Chromium
    apt:
      name: chromium-browser
      state: present
    tags: chromium

  - name: Install FileZilla
    apt:
      name: filezilla
      state: present
    tags: filezilla
