---
- name: Graphic Design Tools Installation Playbook
  hosts: localhost
  become: yes
  tasks:

  - name: Update package list
    apt:
      update_cache: yes

  - name: Install GIMP
    apt:
      name: gimp
      state: present
    tags: gimp

  - name: Install Inkscape
    apt:
      name: inkscape
      state: present
    tags: inkscape

  - name: Install Blender
    apt:
      name: blender
      state: present
    tags: blender

  - name: Install Darktable
    apt:
      name: darktable
      state: present
    tags: darktable

  - name: Instalar Synfig Studio
    apt:
      name: synfigstudio
      state: present
    tags: synfigstudio
