---
- name: Multimedia application installation playbook
  hosts: all
  become: yes
  tasks:

  - name: Update package list
    apt:
      update_cache: yes

  - name: Install OBS Studio
    apt:
      name: obs-studio
      state: present
    tags: obs

  - name: Install Audacity
    apt:
      name: audacity
      state: present
    tags: audacity

  - name: Instalar Kdenlive
    apt:
      name: kdenlive
      state: present
    tags: kdenlive

  - name: Install HandBrake
    apt:
      name: handbrake
      state: present
    tags: handbrake
