---
- name: Install office programs
  hosts: localhost
  become: yes
  tags: office

  tasks:
  - name: Actualizar la lista de paquetes
    apt:
      update_cache: yes

  - name: Install GnuCash
    apt:
      name: gnucash
      state: present

  - name: Install Scribus
    apt:
      name: scribus
      state: present

  - name: Install Calibre
    apt:
      name: calibre
      state: present
